GET http://127.0.0.1:1112/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDQ0MjkwNDY5NTUsImV4cCI6MTcwNDQyOTIyNjk1NSwiaWQiOiI2NTk2MmI1MzQ5N2MzNmQyZGUwZjNlZmMiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGNvbnRhY3QuY29tIn0.TejaKjLV533qykrF0aqf7ftDcBSs1BqmpkdAUbqs82A
